"""empty message

Revision ID: 339c7e54a878
Revises: 641f2b4d07a0
Create Date: 2020-10-28 18:16:13.387400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339c7e54a878'
down_revision = '641f2b4d07a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###
