"""empty message

Revision ID: 641f2b4d07a0
Revises: d8b01cb71108
Create Date: 2020-10-28 18:12:39.273592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641f2b4d07a0'
down_revision = 'd8b01cb71108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
