"""empty message

Revision ID: 911779c72759
Revises: 
Create Date: 2020-10-24 01:46:54.253117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911779c72759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
